storage:
  user: 'u1030_bw4bmA3Qjq'
  pass: '+j8FAaC+9Q+=HixiA8Ek^lyl'
  host: '192.99.100.105'
  db: 's1030_dbdunkin'
  port: 3306

lores:
  prestigeButtomMenu:
    - '&fClique para realizar um Prestigio'
    - ''
    - '&cObs: &fVoce deve estar no ultimo rank'
    - '&cObs2: &fAo realizar o prestigio voce recebera'
    - '&f +1 prestigio e pontos de prestigio. Alem disso'
    - '&fvoce sera enviado para o primeiro rank.'
  prestigeShopMenu:
    - '&eClique aqui para acessar'
    - '&ea area Prestigio Shop'

## Utilize %player% para definir o nome do player no comando
resetCommand: 'pex user %player% group set membro'
resetPoints: 1000