storage:
  user: 'nero'
  pass: 'nero'
  host: '192.168.2.10'
  db: 'sv_mine'
  port: 3306

lores:
  prestigeButtomMenu:
    - '&fClique para realizar um Prestigio'
    - ''
    - '&cObs: &fVoce deve estar no ultimo rank'
    - '&cObs2: &fAo realizar o prestigio voce recebera'
    - '&f +1 prestigio e pontos de prestigio. Alem disso'
    - '&fvoce sera enviado para o primeiro rank.'
  prestigeShopMenu:
    - '&eClique aqui para acessar'
    - '&ea area Prestigio Shop'

## Utilize %player% para definir o nome do player no comando
resetCommand: 'pex user %player% group set membro'
resetPoints: 1000