storage:
  user: 'u1030_bw4bmA3Qjq'
  pass: '+j8FAaC+9Q+=HixiA8Ek^lyl'
  host: '192.99.100.105'
  db: 's1030_dbdunkin'
  port: 3306

lores:
  prestigeButtomMenu:
    - '&eClique para realizar um Prestigio'
    - ''
    - '&cObs: &eVoce deve estar no ultimo rank'
    - '&cObs2: &eAo realizar o prestigio voce recebera'
    - '&e +1 prestigio e pontos de prestigio. Alem disso'
    - '&evoce sera enviado para o primeiro rank.'
  prestigeShopMenu:
    - '&eClique aqui para acessar'
    - '&ea area Prestigio Shop'

## Utilize %player% para definir o nome do player no comando
resetCommand: 'pex user %player% group set membro'