name: NeroPrestigio
main: com.arthuramorim.Main
version: 1.4
author: KingN3R0

commands:
  ppoints:
    description:
  prestigios:
    description:
  prestigio:
    description:
  addppoints:
    description:
  setppoints:
    description:
  addprestige:
    description:
  setprestige:
    description:
  teste:
