name: NeroPrestigio
main: com.arthuramorim.Main
version: 1.7
author: KingN3R0

commands:
  ppoints:
    description: "Ver seus pontos de prestigio"
  prestigios:
    description: "Ver sua quantidade de prestigios"
  prestigio:
    description: "Abre o menu de prestigio do servidor"
  addppoints:
    description: "/addppoints <quantidade> <jogador>"
  setppoints:
    description: "/setppoints <quantidade> <jogador>"
  addprestige:
    description: "/addprestige <quantidade> <jogador>"
  setprestige:
    description: " /setprestige <quantidade> <jogador>"
  teste:
